### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by PikaPirate** [PikaPirate/stardew-valley-tracker#25]
Application icon and name in menu are placeholder
![image](https://user-images.githubusercontent.com/51209736/83418271-3c3e2780-a41b-11ea-938f-08f0abe8653c.png)

**Comment by ThomasCork** [comment]
![ic_launcher-web](https://user-images.githubusercontent.com/23264958/85202685-0bf1f680-b300-11ea-89d0-55414e4a7401.png)

**Comment by ThomasCork** [comment]
![image](https://user-images.githubusercontent.com/23264958/85206342-4b790c80-b319-11ea-8ee9-217bea21e84c.png)
